canonifyurls = false
buildFuture= true
languageCode = "en-us"
title = "mutter.io"
googleAnalytics="UA-53412949-1"

[[menu.main]]
  name        = "Blog"
  identifier   = "blog"
  weight       = 1
  url          = "/blog"

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more informtion take a look at the README.

  # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
  name = "mutter.io"
  description = "Your description"

  # The path must be relative to the static folder
  favicon = "favicon.ico"


  # Navigation
  [params.navigation]
    brand = "mutter.io"

    [params.navigation.links]
      about     = "About"
      services  = "Services"
      portfolio = "Portfolio"
      blog      = "Blog"
      contact   = "Contact"
      team     = "Team"

  [params.footer]
    copywright = "© mutter.io. All rights reserved."

  [[params.footer.social]]
    icon = "fa-twitter"
    link = "//twitter.com/mutter_io"
    display = "mutter_io"

  [[params.footer.social]]
    icon = "fa-linkedin"
    link = "//www.linkedin.com/company/mutter.io"
    display = "mutter.io"

  [[params.footer.social]]
    icon = "fa-envelope-o"
    link = "mailto:info@mutter.io"
    display = "info@mutter.io"
  [[params.footer.social]]
    icon = "fa-phone"
    link = "tel:5125377829"
    display = "(512) 537-7829"
  # Hero section
  [params.hero]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "Soft Spoken Software"
    subtitle   = "A modern development shop focused on delivering... on time and on budget"
    buttonText = "Find out more"


  # About section
  [params.about]
    headline    = "We've got what you need!"
    description = "We are a group of software professionals that have built everything from small websites to subsystems that run on top 10 ecommerce sites."
    buttonText  = "Get started!"

  [[params.team]]
    name= "Jeremy Patton"
    title = "Founder and Managing Director"
    img ="/imgs/team/jp.jpg"
    [[params.team.social]]
      icon = "fa-twitter"
      link = "//twitter.com/pattonjp"
    [[params.team.social]]
      icon = "fa-envelope-o"
      link = "mailto:jeremy@mutter.io"


  # Service section
  [params.services]
    headline = "At your service"

    [[params.services.list]]
      icon = "fa-laptop"
      title = "Custom Solutions"
      description = "Let our team of consultants deliver you next project. We can join you onsite or remote."
      items= [
        "Requirements Gathering",
        "Incremental and Early Delivery",
        "Specializing in Websites and Web applications"
        ]

    [[params.services.list]]
      icon = "fa-cog"
      title = "Modernize Solutions"
      description = "When you find a legacy system is not keeping up with your business Our consultants are experts at giving you a path to growth"

    [[params.services.list]]
      icon = "fa-cloud"
      title = "Cloud Solutions"
      description = "Experts at delivering to the cloud of your choice"

    [[params.services.list]]
      icon = "fa-heart"
      title = "Made with Love"
      description = "Mutter is passionate about open source."


    # Portfolio modals
  [params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
  [params.aside]
    headline = "Our Team"

    [params.aside.button]
      text = "Download now"
      link = "//github.com/digitalcraftsman/hugo-creative-theme"

  # Contact section
  [params.contact]
    headline = "Let's get our partnership started!"
    description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
    phone = "(512) 537-7829"
    email = "info@mutter.io"
